
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/securitycontest
    username: admin    
    password: admin
  jpa :
    hibernate:
      ddl-auto: create